steps:
  # build docker container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.' ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - '$REPO_NAME'
    - '--image'
    - 'eu.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
    - '--region'
    - 'europe-west3'
    - '--platform'
    - 'managed'
    - '--project'
    - 'hardly-evolving-hawk'
    - '--max-instances'
    - '1'
    - '--port'
    - '8080'
    - '--allow-unauthenticated'
images:
  - 'eu.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
